### ISSUE TITLE
Axial LED Model

### ISSUE THREAD

**Issue by seveibar** [tscircuit/jscad-electronics#48]
`<AxiosLed />`

Uses "axial" footprint

![Image](https://github.com/user-attachments/assets/68f1e9f1-11b1-4884-afb0-0f473d5a4734)

**Comment by ni9999** [comment]
Worked on it #59 . This is how the LED looks like![Image](https://github.com/user-attachments/assets/93e047d5-27de-4ec5-87ad-141b6649d4a5)
