### ISSUE TITLE
Axial Capacitor

### ISSUE THREAD

**Issue by seveibar** [tscircuit/jscad-electronics#51]
Note: There are two variants: horizontal and vertical

![Image](https://github.com/user-attachments/assets/62ab0ee2-4fbc-4255-b03c-cf7c50007859)

**Comment by nooras** [comment]
hi @seveibar 
Is it open to work on? can you please provide a doc to setup local server?

**Comment by ni9999** [comment]
@seveibar worked on it #66. Please review it.
